name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar dependencias
        run: npm install

      - name: Correr tests
        run: npm test
      
      -name : "Mostrando variables por defecto de GitHub Actions"
      - run: |
          echo "GitHub Actions - ${{ github.ref }}"
          echo "GitHub Actions - ${{ github.repository }}"
          echo "GitHub Actions - ${{ github.sha }}"
          echo "GitHub Actions - ${{ github.event_name }}"
          echo "GitHub Actions - ${{ github.workflow }}"
      
